import allure
from pages.order_page import OrderPage
from pages.track_page import TrackPage
from pages.main_page import MainPage

class TestOrderPage:
    @allure.title('Проверка позитивного сценария заказа самоката с точкой входа кнопки "Заказать" вверху страницы')
    @allure.description('На странице ищем элементы и проходим по этапам заказа самоката')
    def test_placed_order_first_entry_point_positive_result(self, driver):
        order_page = OrderPage(driver)
        order_page.click_order_button()
        order_page.wait_for_load_first_name_input()
        order_page.set_first_name_input('Тест')
        order_page.set_last_name_input('Тестовый')
        order_page.set_adress_input('Уральская 12')
        order_page.click_metro_station_input()
        order_page.click_station_input()
        order_page.set_phone_input('+79463448752')
        order_page.click_further_button()
        order_page.wait_for_load_when_input()
        order_page.click_when_input()
        order_page.set_when_input()
        order_page.click_rental_period_input()
        order_page.click_two_days_input()
        order_page.click_black_color_checkbox_input()
        order_page.set_comment_input('тест')
        order_page.click_order_middle_button()
        order_page.wait_for_load_yes_button()
        order_page.click_yes_button()
        order_page.wait_for_load_placed_order_title()
        order_page.check_placed_order_title()
        order_page.click_view_status_button()
        track_page = TrackPage(driver)
        track_page.wait_for_load_view_button()
        track_page.click_scooter_logo_button()
        track_page.check_main_page_scooter()

    @allure.title('Проверка позитивного сценария заказа самоката с точкой входа кнопки "Заказать" внизу страницы')
    @allure.description('На странице ищем элементы и проходим по этапам заказа самоката')
    def test_placed_order_second_entry_point_positive_result(self, driver):
        main_page = MainPage(driver)
        main_page.scroll_order_ultrabig_button()
        main_page.click_order_ultrabig_button()
        order_page = OrderPage(driver)
        order_page.wait_for_load_first_name_input()
        order_page.set_first_name_input('Иван')
        order_page.set_last_name_input('Иванов')
        order_page.set_adress_input('Первомайская 23')
        order_page.click_metro_station_input()
        order_page.click_station_input()
        order_page.set_phone_input('+79348962148')
        order_page.click_further_button()
        order_page.wait_for_load_when_input()
        order_page.click_when_input()
        order_page.set_when_input()
        order_page.click_rental_period_input()
        order_page.click_three_days_input()
        order_page.click_grey_color_checkbox_input()
        order_page.set_comment_input('комментарий')
        order_page.click_order_middle_button()
        order_page.wait_for_load_yes_button()
        order_page.click_yes_button()
        order_page.wait_for_load_placed_order_title()
        order_page.check_placed_order_title()
        order_page.click_view_status_button()
        track_page = TrackPage(driver)
        track_page.wait_for_load_view_button()
        track_page.click_yandex_logo_button()
        track_page.check_main_page_dzen()
